Show a better error when MODULE.bazel is missing
Previously, Bazel would error out with this message if it couldn't find
a MODULE.bazel (e.g. in the root module):

```
ERROR: unknown error during computation of main repo mapping
```

Closes #16080.

PiperOrigin-RevId: 466910762
Change-Id: I6fe4fc3e26b5fd203945d7031a9b2a086dce4d31